version: '2.4'

services:
  app:
    image: nytexclamations
    container_name: nytexclamations
    restart: always
    build: .
    stdin_open: true
    tty: true
    ports:
      - 9000:9000
    volumes:
      - .:/app
